#:kivy 2.3.0
#:include basewidget.kv

<SimulatorDataLabel@BoxLayout>:
    orientation: "horizontal"

    size_hint_y: None
    height: set_height

    StrFrameView:
        text: "楽曲"

    StrFrameView:
        text: "センター"

    StrFrameView:
        text: "左隣り"

    StrFrameView:
        text: "右隣り"

    StrFrameView:
        text: "左端"

    StrFrameView:
        text: "右端"

    StrFrameView:
        text: "ゲスト"

    StrFrameView:
        text: "状態"

    StrFrameView:
        text: "スコア"

<SimulatorDataViewclass>:
    musicname: musicname
    centerepisode: centerepisode
    leftepisode: leftepisode
    rightepisode: rightepisode
    leftendepisode: leftendepisode
    rightendepisode: rightendepisode
    guestepisode: guestepisode
    progressview: progressview
    scoreview: scoreview

    canvas.before:
        Color:
            rgba: (0.0, 0.9, 0.1, 0.3) if self.selected else (0, 0, 0, 0)
        Rectangle:
            pos: self.pos
            size: self.size

    orientation: "horizontal"
    size_hint_y: None
    height: set_height

    StrFrameView:
        id: musicname
        text: "楽曲"

    StrFrameView:
        id: centerepisode
        text: "センター"

    StrFrameView:
        id: leftepisode
        text: "左隣り"

    StrFrameView:
        id: rightepisode
        text: "右隣り"

    StrFrameView:
        id: leftendepisode
        text: "左端"

    StrFrameView:
        id: rightendepisode
        text: "右端"

    StrFrameView:
        id: guestepisode
        text: "ゲスト"

    StrFrameView:
        id: progressview
        text: "状態"

    StrFrameView:
        id: scoreview
        text: "スコア"

<SimulatorView>:
    simulatordataviewlabel: simulatordataviewlabel
    simulatordataviews: simulatordataviews

    orientation: "vertical"

    SimulatorDataLabel:
        id: simulatordataviewlabel

    RecycleView:
        id: simulatordataviews
        bar_width: set_height * 2
        do_scroll_x: False
        do_scroll_y: True

        viewclass: "SimulatorDataViewclass"
        SelectableRecycleBoxLayout:
            default_size_hint: 1, None
            default_size: None, set_height
            size_hint_y: None
            height: self.minimum_height
            orientation: "vertical"
            multiselect: False
            touch_multiselect: False
            touch_deselect_last: True
            key_selection: "status"
